/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jianshengd_ndk_HelloNdk */

#ifndef _Included_com_example_jianshengd_ndk_HelloNdk
#define _Included_com_example_jianshengd_ndk_HelloNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jianshengd_ndk_HelloNdk
 * Method:    getMaxInt
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jianshengd_ndk_HelloNdk_getMaxInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
